export type WeddingForm = {
  nombre: string;
  email: string;
  telNovio: string;
  telNovia: string;
  fecha: string;
  lugar: string;
  novia: string;
  novio: string;
  ceremonia: string;
  horaSalidaNovio: string;
  horaSalidaNovia: string;
  horaCeremonia: string;
  horaCoctel: string;
  horaBarraLibre: string;
  detalles: string;
  tipoPack: string;
  fechaPreboda: string;
  lugarPreboda: string;
  detallesPreboda: string;
  fechaPostboda: string;
  lugarPostboda: string;
  detallesPostboda: string;
  status: string;
};